// Generated by CoffeeScript 1.6.2
(function() {
  var Instance, Instances, flatten, outcome, toarray,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  outcome = require("outcome");

  toarray = require("toarray");

  flatten = require("flatten");

  Instance = require("./instance");

  Instances = (function(_super) {
    __extends(Instances, _super);

    /*
    */


    function Instances(region) {
      this.region = region;
      Instances.__super__.constructor.call(this, {
        modelClass: Instance
      });
    }

    /*
    */


    Instances.prototype._load2 = function(options, next) {
      var search;

      search = {};
      if (options._id) {
        search["InstanceId.1"] = options._id;
      }
      return this.region.api.call("DescribeInstances", search, outcome.e(next).s(function(result) {
        var instances;

        instances = toarray(result.reservationSet.item);
        instances = flatten(instances.map(function(instance) {
          return instance.instancesSet.item;
        })).map(function(instance) {
          return {
            _id: instance.instanceId,
            imageId: instance.imageId,
            state: instance.instanceState.name,
            dnsName: instance.dnsName,
            type: instance.instanceType,
            launchTime: new Date(instance.launchTime),
            architecture: instance.architecture
          };
        });
        if (!options._id) {
          instances = instances.filter(function(instance) {
            return instance.state !== "terminated";
          });
        }
        return next(null, instances);
      }));
    };

    return Instances;

  })(require("../../base/collection"));

  module.exports = Instances;

}).call(this);
