// Generated by CoffeeScript 1.6.2
(function() {
  var Image, async, outcome, toarray, _ref,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  outcome = require("outcome");

  toarray = require("toarray");

  async = require("async");

  /*
  
  Server States:
  
  +--------+---------------+
  |  Code  |     State     |
  +--------+---------------+
  |   ?    |    pending    | 
  |   ?    |    available  |
  +--------+---------------+
  */


  Image = (function(_super) {
    __extends(Image, _super);

    function Image() {
      this._migrateToRegion = __bind(this._migrateToRegion, this);      _ref = Image.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Image.prototype.createInstance = function(options, next) {
      var _this = this;

      if (arguments.length === 1) {
        next = options;
        options = {};
      }
      options.imageId = this.get("_id");
      options.tags = this.get("tags");
      return this.wait({
        state: "available"
      }, function() {
        return _this.collection.region.instances.create(options, next);
      });
    };

    /*
    */


    Image.prototype.migrate = function(regions, next) {
      var _this = this;

      regions = toarray(regions);
      return this.wait({
        state: "available"
      }, outcome.e(next).s(function() {
        return _this.region.collection.find({
          name: {
            $in: regions
          }
        }, outcome.e(next).s(function(regions) {
          return async.map(regions, _this._migrateToRegion, next);
        }));
      }));
    };

    /*
    */


    Image.prototype._migrateToRegion = function(region, next) {
      var o,
        _this = this;

      o = outcome.e(next);
      return region.api.call("CopyImage", {
        "SourceRegion": this.get("region"),
        "SourceImageId": this.get("_id"),
        "Description": this.get("description") || this.get("_id"),
        "Name": this.get("name") || this.get("_id")
      }, o.s(function(image) {
        return region.images.waitForOne({
          _id: image.imageId
        }, o.s(function(image) {
          return image.wait({
            state: "available"
          }, o.s(function() {
            return image.tag(_this.get("tags"), next);
          }));
        }));
      }));
    };

    /*
    */


    Image.prototype._destroy = function(next) {
      return this.api.call("DeregisterImage", {
        "ImageId": this.get("_id")
      }, next);
    };

    return Image;

  })(require("../../base/regionModel"));

  module.exports = Image;

}).call(this);
