// Generated by CoffeeScript 1.4.0
(function() {
  var BaseModel, Migrator, Tags, allRegions, async, createInstance, gumbo, outcome, stepc, tagsToObject, toarray,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  stepc = require("stepc");

  outcome = require("outcome");

  allRegions = require("../../utils/regions");

  createInstance = require("../../utils/createInstance");

  BaseModel = require("../base/model");

  Tags = require("../tags");

  tagsToObject = require("../../utils/tagsToObject");

  toarray = require("toarray");

  async = require("async");

  Migrator = require("./migrator");

  /*
  
  Server States:
  
  +--------+---------------+
  |  Code  |     State     |
  +--------+---------------+
  |   ?    |    pending    | 
  |   ?    |    available  |
  +--------+---------------+
  */


  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(collection, region, item) {
      _Class.__super__.constructor.call(this, collection, region, item);
      this.tags = new Tags(this);
    }

    /*
        Function: createServer
      
        creates a new server from the AMI
    
        Parameters:
    */


    _Class.prototype.createInstance = function(options, callback) {
      var _this = this;
      if (arguments.length === 1) {
        callback = options;
        options = {};
      }
      ectwo_log.log("%s: create server", this.region.name);
      options.imageId = this.get("_id");
      options.tags = tagsToObject(this.get("tags") || []);
      return this.waitUntilSync({
        state: "available"
      }, function() {
        return createInstance(_this.region, options, callback);
      });
    };

    /*
    */


    _Class.prototype.getSnapshot = function(callback) {
      var _this = this;
      return this.region.snapshots.load(outcome.e(callback).s(function() {
        return _this.region.snapshots.findOne({
          imageId: _this.get("_id")
        }, outcome.e(callback).s(function(snapshot) {
          if (!snapshot) {
            return callback(new Error("unable to fetch snapshot"));
          }
          return callback(null, snapshot);
        }));
      }));
    };

    /*
    */


    _Class.prototype.getOneSpotPricing = function(search, callback) {
      if (typeof search === "function") {
        callback = search;
        search = {};
      }
      search.platform = this.get("platform");
      return this.region.spotRequests.pricing.findOne(search, callback);
    };

    /*
    */


    _Class.prototype.createSpotRequest = function(options, callback) {
      options.imageId = this.get("imageId");
      return this.region.spotRequests.create(options, callback);
    };

    /*
       TODO - this needs to be a job. Migrating instances
       may take a long time, and we can't have this shoved into memory. - perhaps
       copy a snapshot & provide directions for initialization in the description.
    */


    _Class.prototype.migrate = function(regions, callback) {
      var _this = this;
      return this.getSnapshot(outcome.e(callback).s(function(snapshot) {
        return async.map(toarray(regions), (function(region, next) {
          return region.snapshots.copy({
            "_id": snapshot.get("_id"),
            "region": snapshot.get("region"),
            "description": _this.get("description")
          }, outcome.e(next).s(function(snapshot) {
            return next(null, new Migrator(_this, snapshot));
          }));
        }), callback);
      }));
    };

    /*
        Function: removes the AMI 
    
        Parameters:
    */


    _Class.prototype.destroy = function(callback) {
      return this._ec2.call("DeregisterImage", {
        "ImageId": this.get("_id")
      }, callback);
    };

    return _Class;

  })(BaseModel);

}).call(this);
