// Generated by CoffeeScript 1.4.0
(function() {
  var ImageModel, gumbo, outcome, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  _ = require("underscore");

  ImageModel = require("./image");

  outcome = require("outcome");

  /*
   A collection of ALL Amazon Machine Images
  */


  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      this.region = region;
      this.ec2 = region.ec2;
      _Class.__super__.constructor.call(this, [], _.bind(this._createModel, this));
      this._sync = this.synchronizer({
        uniqueKey: "imageId",
        load: _.bind(this._load, this)
      });
    }

    /*
       Starts the synchronization process
    */


    _Class.prototype.load = function(callback) {
      return this._sync.start(callback);
    };

    /*
    */


    _Class.prototype._createModel = function(collection, item) {
      item.region = this.region.get("name");
      return new ImageModel(collection, this.region, item);
    };

    /*
       Loads the remote collection
    */


    _Class.prototype._load = function(onLoad) {
      var _this = this;
      return this.ec2.call("DescribeImages", {
        "Owner.1": "self"
      }, outcome.e(onLoad).s(function(result) {
        var images;
        if (!result.imagesSet.item) {
          return onLoad(null, []);
        }
        images = !(result.imagesSet.item instanceof Array) ? [result.imagesSet.item] : result.imagesSet.item;
        return onLoad(null, images);
      }));
    };

    return _Class;

  })(gumbo.Collection);

}).call(this);
