// Generated by CoffeeScript 1.4.0
(function() {
  var BaseCollection, ImageModel, createInstance, gumbo, outcome, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  _ = require("underscore");

  ImageModel = require("./image");

  outcome = require("outcome");

  createInstance = require("../../utils/createInstance");

  BaseCollection = require("../base/collection");

  /*
   A collection of ALL Amazon Machine Images
  */


  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      _Class.__super__.constructor.call(this, region, {
        uniqueKey: "imageId",
        modelClass: ImageModel
      });
    }

    /*
       creates a new instance
    */


    _Class.prototype.createInstance = function(options, callback) {
      if (typeof options !== "object") {
        throw new Error("options must be an object");
      }
      return createInstance(this, options, callback);
    };

    /*
       Loads the remote collection
    */


    _Class.prototype._load = function(onLoad) {
      var _this = this;
      return this.ec2.call("DescribeImages", {
        "Owner.1": "self"
      }, outcome.e(onLoad).s(function(result) {
        var images;
        if (!result.imagesSet.item) {
          return onLoad(null, []);
        }
        images = !(result.imagesSet.item instanceof Array) ? [result.imagesSet.item] : result.imagesSet.item;
        return onLoad(null, images);
      }));
    };

    return _Class;

  })(BaseCollection);

}).call(this);
