// Generated by CoffeeScript 1.6.2
(function() {
  var packages;

  packages = require("packages");

  module.exports = function(ectwo) {
    return packages().require({
      ectwo: ectwo
    }).require(__dirname + "/packages").load();
  };

}).call(this);
