// Generated by CoffeeScript 1.4.0
(function() {
  var BaseSync,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseSync = require("../base/sync");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    /*
        Function: updates 
    
        Updates the collection with the newest server info from EC2.
        Note - this is really only important for inserting NEW ec2 instances, since
        each server does a fetch for new information periodically
    
        Parameters:
    */


    _Class.prototype.update = function(callback) {
      var _this = this;
      return this.ec2.call("DescribeImages", {
        "Owner.1": "self"
      }, function(err, result) {
        return console.log(result.imagesSet.item);
      });
    };

    return _Class;

  })(BaseSync);

}).call(this);
