// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {
    /*
    */

    function _Class(item) {
      this.item = item;
    }

    /*
    */


    _Class.prototype.update = function() {};

    return _Class;

  })();

}).call(this);
