// Generated by CoffeeScript 1.4.0
(function() {
  var sift;

  sift = require("sift");

  module.exports = (function() {
    /*
    */

    function _Class() {
      this._classes = [];
    }

    /*
    */


    _Class.prototype.addControllerClass = function(search, clazz) {
      return this._classes.push({
        search: sift(search),
        clazz: clazz
      });
    };

    /*
    */


    _Class.prototype.addControllers = function(item) {
      var data, _i, _len, _ref, _results;
      data = item.get();
      _ref = this._classes;
      _results = [];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        item = _ref[_i];
        if (item.search.test(data)) {
          _results.push(data.controllers.add(new item.clazz(item)));
        } else {
          _results.push(void 0);
        }
      }
      return _results;
    };

    return _Class;

  })();

}).call(this);
