// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = (function() {
    /*
    */

    function _Class(item) {
      this.item = item;
      this._controllers = {};
    }

    /*
       updates the controllers after the item changes
    */


    _Class.prototype.update = function() {};

    /*
    */


    _Class.prototype.add = function(controller) {
      return this._controllers[controller.name] = controller;
    };

    /*
    */


    _Class.prototype.get = function(name) {
      return this._controllers[name];
    };

    /*
    */


    _Class.prototype.remove = function(name) {
      return delete this._controllers[name];
    };

    return _Class;

  })();

}).call(this);
