// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(collection, items, idKey, callback) {
    var objectIds, objectsById, search;
    objectsById = {};
    objectIds = items.map(function(item) {
      objectsById[item[idKey]] = item;
      return item[idKey];
    });
    search = {};
    search[idKey] = {
      $in: objectIds
    };
    collection.find(search).sync().forEach(function(image) {
      var id;
      id = image.get(idKey);
      image.update(objectsById[id]);
      return items.splice(items.indexOf(objectsById[id]), 1);
    });
    return collection.insert(items, callback).exec(callback);
  };

}).call(this);
