// Generated by CoffeeScript 1.4.0
(function() {
  var ServerModel, comerr, gumbo, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  ServerModel = require("./server");

  comerr = require("comerr");

  _ = require("underscore");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      this.region = region;
      this.ec2 = region.ec2;
      _Class.__super__.constructor.call(this, [], _.bind(this._createModel, this));
      this._sync = this.synchronizer({
        uniqueKey: "instanceId",
        load: _.bind(this._load, this),
        timeout: 1000
      });
    }

    /*
    	 Function: load
    */


    _Class.prototype.load = function(callback) {
      return this._sync.start(callback);
    };

    /*
    */


    _Class.prototype._createModel = function(collection, item) {
      item.region = this.region.get("name");
      return new ServerModel(collection, this.region, item);
    };

    /*
    */


    _Class.prototype._load = function(onLoad) {
      var _this = this;
      return this.ec2.call("DescribeInstances", {}, function(err, result) {
        var instances, serversById;
        serversById = {};
        if (!result.reservationSet.item) {
          return onLoad(null, []);
        }
        instances = !(result.reservationSet.item instanceof Array) ? [result.reservationSet.item] : result.reservationSet.item;
        instances = instances.map(function(instance) {
          return instance.instancesSet.item;
        });
        return onLoad(null, instances);
      });
    };

    return _Class;

  })(gumbo.Collection);

}).call(this);
