// Generated by CoffeeScript 1.6.2
(function() {
  var Addresses, BaseModel, Images, Instances, KeyPairs, Region, SecurityGroups, Snapshots, SpotRequests, aws, outcome, stepc,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseModel = require("../base/model");

  aws = require("aws-lib");

  Instances = require("./instances");

  Images = require("./images");

  KeyPairs = require("./keyPairs");

  SecurityGroups = require("./securityGroups");

  Addresses = require("./addresses");

  SpotRequests = require("./spotRequests");

  Snapshots = require("./snapshots");

  stepc = require("stepc");

  outcome = require("outcome");

  Region = (function(_super) {
    __extends(Region, _super);

    /*
    */


    function Region(data, collection) {
      var ops, options;

      Region.__super__.constructor.call(this, data, collection);
      options = collection.ectwoOptions;
      ops = {
        host: "ec2." + (this.get('_id')) + ".amazonaws.com",
        key: options.key,
        secret: options.secret,
        version: "2013-02-01"
      };
      this.api = aws.createEC2Client(ops.key, ops.secret, {
        host: ops.host,
        version: ops.version
      });
      this.instances = new Instances(this);
      this.images = new Images(this);
      this.keyPairs = new KeyPairs(this);
      this.securityGroups = new SecurityGroups(this);
      this.addresses = new Addresses(this);
      this.snapshots = new Snapshots(this);
    }

    /*
    */


    Region.prototype.createInstance = function(options, next) {
      var newInstanceId, o, self;

      o = outcome.e(next);
      newInstanceId = null;
      self = this;
      return stepc.async(function() {
        return self.api.call("RunInstances", {
          ImageId: options.imageId,
          MinCount: options.count || 1,
          MaxCount: options.count || 1,
          InstanceType: options.flavor || options.type || "t1.micro"
        }, this);
      }, o.s(function(result) {
        newInstanceId = result.instancesSet.item.instanceId;
        return self.instances.wait({
          _id: newInstanceId
        }, this);
      }), o.s(function(instance) {
        return next(null, instance);
      }), next);
    };

    return Region;

  })(BaseModel);

  module.exports = Region;

}).call(this);
