// Generated by CoffeeScript 1.4.0
(function() {
  var AMIs, Instances, async, cstep, gumbo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  async = require("async");

  Instances = require("./instances");

  AMIs = require("./amis");

  cstep = require("cstep");

  gumbo = require("gumbo");

  /*
  Amazon doesn't have a single API to access to all regions, so we have to provide
  a business delegate with a specific endpoint to the region we want to connect to. With EC2, all of them.
  */


  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(collection, options) {
      this.collection = collection;
      this.options = options;
      _Class.__super__.constructor.call(this, collection, {
        name: options.name
      });
      this.ec2 = options.ec2;
      this.amis = new AMIs(this);
      this.instances = new Instances(this);
    }

    /*
    */


    _Class.prototype.load = cstep(function(callback) {
      var _this = this;
      ectwo_log.log("%s: loading", this.get("name"));
      async.forEach([this.amis, this.servers], (function(loadable, next) {
        return loadable.load(next);
      }), callback);
      return this;
    });

    return _Class;

  })(gumbo.BaseModel);

}).call(this);
