// Generated by CoffeeScript 1.4.0
(function() {
  var BaseCollection, SnapShot, SpotRequest, outcome, toarray,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseCollection = require("../base/collection");

  SpotRequest = require("./spotRequest");

  outcome = require("outcome");

  toarray = require("toarray");

  SnapShot = require("./snapshot");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      _Class.__super__.constructor.call(this, region, {
        modelClass: SnapShot
      });
    }

    _Class.prototype._load = function(options, onLoad) {};

    return _Class;

  })(BaseCollection);

}).call(this);
