// Generated by CoffeeScript 1.6.2
(function() {
  var Instances,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Instances = (function(_super) {
    __extends(Instances, _super);

    /*
    */


    function Instances(region) {
      this.region = region;
      Instances.__super__.constructor.call(this);
    }

    return Instances;

  })(require("../../base/collection"));

  module.exports = Instances;

}).call(this);
