// Generated by CoffeeScript 1.6.2
(function() {
  var Snapshot, outcome, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  outcome = require("outcome");

  Snapshot = (function(_super) {
    __extends(Snapshot, _super);

    function Snapshot() {
      _ref = Snapshot.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
    */


    Snapshot.prototype.createVolume = function(options, next) {
      if (arguments.length === 1) {
        next = options;
        options = {};
      }
      options.snapshotId = this.get("_id");
      return this.region.volumes.create(options, next);
    };

    /*
    */


    Snapshot.prototype._destroy = function(next) {
      return this.api.call("DeleteSnapshot", {
        "SnapshotId.1": this.get("_id")
      }, next);
    };

    return Snapshot;

  })(require("../../base/regionModel"));

  module.exports = Snapshot;

}).call(this);
