// Generated by CoffeeScript 1.4.0
(function() {
  var cstep;

  cstep = require("cstep");

  module.exports = (function() {
    /*
        Function: 
    
        Parameters:
    */

    function _Class(region, collection) {
      this.region = region;
      this.collection = collection;
      cstep(this).add(this.region);
    }

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype.find = cstep(function(query, callback) {});

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype.findOne = cstep(function(query, callback) {});

    return _Class;

  })();

}).call(this);
