// Generated by CoffeeScript 1.4.0
(function() {
  var Region, allRegions, async, aws;

  aws = require("aws-lib");

  async = require("async");

  Region = require("./region");

  allRegions = require("../utils/regions");

  module.exports = (function() {
    /*
        Function: Constructor
    
        Parameters:
          options
            key - the EC2 key
            secret - the EC2 private key
          whitelist The whitelist of ec2 regions we want to deploy servers to
    */

    function _Class(options, whitelist) {
      this.options = options;
      this.whitelist = whitelist ? whitelist : allRegions;
      this.load();
    }

    _Class.prototype.load = function(callback) {
      var _this = this;
      if (callback == null) {
        callback = (function() {});
      }
      this.regions = [];
      return async.forEach(this.whitelist, (function(regStr, next) {
        var ec2, host;
        host = "ec2." + regStr + ".amazonaws.com";
        ec2 = aws.createEC2Client(_this.options.key, _this.options.secret, {
          host: host
        });
        return _this.regions.push(new Region(regStr, ec2).load(next));
      }), callback);
    };

    return _Class;

  })();

}).call(this);
