// Generated by CoffeeScript 1.4.0
(function() {
  var Region, allRegions, async, aws, gumbo;

  aws = require("aws-lib");

  async = require("async");

  Region = require("./region");

  allRegions = require("../utils/regions");

  gumbo = require("gumbo");

  module.exports = (function() {
    /*
        Function: Constructor
    
        Parameters:
          options
            key - the EC2 key
            secret - the EC2 private key
          whitelist The whitelist of ec2 regions we want to deploy servers to
    */

    function _Class(options, whitelist) {
      this.options = options;
      this.whitelist = whitelist ? whitelist : allRegions;
      this.regions = gumbo.collection([]);
      this.load();
    }

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype.load = function(callback) {
      var _this = this;
      if (callback == null) {
        callback = (function() {});
      }
      return async.forEach(this.whitelist, (function(regStr, next) {
        var ec2, host;
        host = "ec2." + regStr + ".amazonaws.com";
        ec2 = aws.createEC2Client(_this.options.key, _this.options.secret, {
          host: host
        });
        return _this.regions.insert(new Region(regStr, ec2).load(next)).exec(next);
      }), callback);
    };

    return _Class;

  })();

}).call(this);
