// Generated by CoffeeScript 1.4.0
(function() {
  var gumbo, outcome, stepc,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  stepc = require("stepc");

  outcome = require("outcome");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
        Function: 
    
        Parameters:
    */


    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    return _Class;

  })(gumbo.BaseModel);

  ({
    constructor: function(collection, region, item) {
      this.region = region;
      return constructor.__super__.constructor.call(this, collection, item);
    },
    /*
        Function: createServer
    
        Parameters:
    */

    createServer: function(options, callback) {
      var _this = this;
      return stepc(function() {
        return _this._ec2.call("RunInstances", {
          "ImageId": _this.get("imageId"),
          "MinCount": options.count || 1,
          "MaxCount": options.count || 1,
          "InstanceType": options.flavor || "m1.small"
        }, callback);
      });
    },
    /*
        Function: removes the AMI 
    
        Parameters:
    */

    deRegister: function(callback) {
      return this._ec2.call("DeregisterImage", {
        "ImageId": this.get("imageId")
      }, callback);
    }
  });

}).call(this);
