// Generated by CoffeeScript 1.4.0
(function() {
  var dref;

  dref = require("dref");

  module.exports = (function() {
    /*
    */

    function _Class(collection) {
      this.collection = collection;
    }

    /*
    */


    _Class.prototype.get = function(key) {
      if (!key) {
        return this.data;
      }
      return dref.get(key);
    };

    /*
    */


    _Class.prototype.set = function(key, value) {
      if (arguments.length === 1) {
        return this.data = key;
      } else {
        return dref.set(key, value);
      }
    };

    return _Class;

  })();

}).call(this);
