// Generated by CoffeeScript 1.4.0
(function() {
  var BaseCollection, KeyPair, gumbo, toarray, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require("underscore");

  gumbo = require("gumbo");

  KeyPair = require("./keyPair");

  toarray = require("toarray");

  BaseCollection = require("../base/collection");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      _Class.__super__.constructor.call(this, region, {
        modelClass: KeyPair,
        name: "keyPair"
      });
    }

    /*
    */


    _Class.prototype._load = function(options, onLoad) {
      var search;
      search = {};
      if (options._id) {
        search["KeyName.1"] = options._id;
      }
      return this.ec2.call("DescribeKeyPairs", search, this._o.e(onLoad).s(function(result) {
        var keySets;
        keySets = toarray(result.keySet.item).map(function(keySet) {
          return {
            _id: keySet.keyName,
            name: keySet.keyName,
            fingerprint: keySet.keyFingerprint
          };
        });
        return onLoad(null, keySets);
      }));
    };

    /*
    */


    _Class.prototype.create = function(optionsOrName, callback) {
      var onKey, options,
        _this = this;
      if (typeof optionsOrName === "string") {
        options = {
          name: optionsOrName
        };
      } else {
        options = optionsOrName;
      }
      onKey = this._o.e(callback).s(function(result) {
        return _this.syncAndFindOne({
          name: options.name
        }, callback);
      });
      if (options.material) {
        return this.ec2.call("ImportKeyPair", {
          KeyName: options.name,
          PublicKeyMaterial: options.material
        }, onKey);
      } else {
        return this.ec2.call("CreateKeyPair", {
          KeyName: options.name
        }, onKey);
      }
    };

    return _Class;

  })(BaseCollection);

}).call(this);
