// Generated by CoffeeScript 1.4.0
(function() {
  var BaseCollection, KeyPair, gumbo, outcome, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  _ = require("underscore");

  KeyPair = require("./keyPair");

  BaseCollection = require("../base/collection");

  outcome = require("outcome");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      _Class.__super__.constructor.call(this, region, {
        uniqueKey: "keyName",
        modelClass: KeyPair
      });
    }

    /*
    */


    _Class.prototype._load = function(onLoad) {
      return this.ec2.call("DescribeKeyPairs", {}, outcome.e(onLoad).s(function(result) {
        var keySets;
        if (!result.keySet.item) {
          return onLoad(null, []);
        }
        keySets = result.keySet.item instanceof Array ? result.keySet.item : [result.keySet.item];
        return onLoad(null, keySets);
      }));
    };

    /*
    */


    _Class.prototype.create = function(optionsOrName, callback) {
      var onKey, options,
        _this = this;
      if (typeof optionsOrName === "string") {
        options = {
          name: optionsOrName
        };
      } else {
        options = optionsOrName;
      }
      onKey = outcome.e(callback).s(function(result) {
        return _this.syncAndFindOne({
          keyName: options.name
        }, callback);
      });
      if (options.material) {
        return this.ec2.call("ImportKeyPair", {
          KeyName: options.name,
          PublicKeyMaterial: options.material
        }, onKey);
      } else {
        return this.ec2.call("CreateKeyPair", {
          KeyName: options.name
        }, onKey);
      }
    };

    return _Class;

  })(BaseCollection);

}).call(this);
