// Generated by CoffeeScript 1.4.0
(function() {
  var BaseModel, gumbo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  BaseModel = require("../base/model");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    function _Class() {
      return _Class.__super__.constructor.apply(this, arguments);
    }

    /*
       destroys the keypair
    */


    _Class.prototype.destroy = function(callback) {
      var _this = this;
      return this._ec2.call("DeleteKeyPair", {
        KeyName: this.get("name")
      }, outcome.e(callback).s(function() {
        return _this.collection.load(callback);
      }));
    };

    return _Class;

  })(BaseModel);

}).call(this);
