// Generated by CoffeeScript 1.6.2
(function() {
  var BaseModel, gumbo, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  BaseModel = require("../base/model");

  /*
  */


  module.exports = (function(_super) {
    __extends(_Class, _super);

    function _Class() {
      _ref = _Class.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    /*
     destroys the keypair
    */


    _Class.prototype.destroy = function(callback) {
      var _this = this;

      return this._ec2.call("DeleteKeyPair", {
        KeyName: this.get("name")
      }, this._o.e(callback).s(function() {
        return _this.collection.load(callback);
      }));
    };

    return _Class;

  })(BaseModel);

}).call(this);
