// Generated by CoffeeScript 1.4.0
(function() {
  var ImageModel, Sync, gumbo, _;

  Sync = require("./sync");

  gumbo = require("gumbo");

  _ = require("underscore");

  ImageModel = require("./ami");

  module.exports = (function() {
    /*
    */

    function _Class(region) {
      this.region = region;
      this.collection = gumbo.collection([], _.bind(this._createModel, this));
      this.sync = new Sync(this);
    }

    /*
    */


    _Class.prototype.load = function(callback) {
      return this.sync.load(callback);
    };

    /*
    */


    _Class.prototype._createModel = function(collection, item) {
      item.region = this.region.name;
      return new ImageModel(collection, this.region, item);
    };

    return _Class;

  })();

}).call(this);
