// Generated by CoffeeScript 1.4.0
(function() {
  var Regions, async, aws;

  async = require("async");

  aws = require("aws-lib");

  Regions = require("./regions");

  module.exports = function(options, regions) {
    return new Regions(options, regions);
  };

}).call(this);
