// Generated by CoffeeScript 1.6.2
(function() {
  var fs, mkdirp, outcome, path;

  fs = require("fs");

  outcome = require("outcome");

  mkdirp = require("mkdirp");

  path = require("path");

  exports.require = ["ectwo"];

  exports.load = function(ectwo) {
    return ectwo.fastener.options().keyPair.save = {
      type: "keyPair",
      call: function(keyPath, next) {
        var e, onSave,
          _this = this;

        if (arguments.length === 1) {
          next = keyPath;
          keyPath = "~/keys/" + (this.get('region')) + "/" + (this.get('name')) + ".pem";
        }
        onSave = function() {
          next(null, _this);
          return console.log("save keypair to %s", keyPath);
        };
        keyPath = keyPath.replace("~", process.env.HOME);
        try {
          mkdirp.sync(path.dirname(keyPath));
        } catch (_error) {
          e = _error;
          console.log(e.stack);
        }
        return fs.writeFile(keyPath, this.get("material"), outcome.e(next).s(onSave));
      }
    };
  };

}).call(this);
