// Generated by CoffeeScript 1.6.2
(function() {
  var ECTwo, Regions, bindable, fastener,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  bindable = require("bindable");

  Regions = require("./regions");

  fastener = require("./fastener");

  ECTwo = (function(_super) {
    __extends(ECTwo, _super);

    /*
    */


    function ECTwo(options) {
      this.options = options;
      ECTwo.__super__.constructor.call(this);
      this.regions = new Regions(this.options);
    }

    /*
    */


    ECTwo.prototype.chain = function() {
      return fastener.wrap("ectwo", this);
    };

    return ECTwo;

  })(bindable.Object);

  module.exports = function(config) {
    return new ECTwo(config);
  };

  module.exports.fastener = fastener;

}).call(this);
