// Generated by CoffeeScript 1.4.0
(function() {
  var ECTwo, EventEmitter, JoinedRegionCollection, Region, allRegions, async, aws, cstep, gumbo, outcome, winston, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require("underscore");

  aws = require("aws-lib");

  async = require("async");

  gumbo = require("gumbo");

  cstep = require("cstep");

  Region = require("./region");

  outcome = require("outcome");

  winston = require("winston");

  allRegions = require("./utils/regions");

  EventEmitter = require("events").EventEmitter;

  JoinedRegionCollection = require("./joinedRegionCollection");

  /*
  */


  winston.remove(winston.transports.Console);

  winston.add(winston.transports.Console, {
    silent: !process.env.LOG_ECTWO
  });

  outcome.logAllErrors(!!process.env.LOG_ECTWO);

  /*
  */


  ECTwo = (function(_super) {

    __extends(ECTwo, _super);

    /*
        Function: Constructor
    
        Parameters:
          options
            key - the EC2 key
            secret - the EC2 private key
          whitelist The whitelist of ec2 regions we want to deploy servers to
    */


    function ECTwo(options, whitelist) {
      var collectionName, _i, _len, _ref;
      this.options = options;
      this.whitelist = whitelist ? whitelist : allRegions;
      this.regions = gumbo.collection([], _.bind(this._createRegionModel, this));
      _ref = ["instances", "images", "keyPairs", "securityGroups", "addresses", "spotRequests", "snapshots"];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        collectionName = _ref[_i];
        this[collectionName] = new JoinedRegionCollection(this, collectionName);
      }
      this._o = outcome.e(this);
      this.regions.loader({
        load: _.bind(this.load, this)
      }).load();
      this._loadRegions();
      this.instances.load();
      this.images.load();
    }

    /*
        Function: 
    
        Parameters:
    */


    ECTwo.prototype.load = cstep(function(callback) {
      var _this = this;
      return callback(null, this.whitelist.map(function(regStr) {
        var ec2, host;
        host = "ec2." + regStr + ".amazonaws.com";
        ec2 = aws.createEC2Client(_this.options.key, _this.options.secret, {
          host: host,
          version: "2013-02-01"
        });
        return {
          name: regStr,
          ec2: ec2,
          _id: regStr
        };
      }));
    });

    /*
    */


    ECTwo.prototype._createRegionModel = function(collection, options) {
      return new Region(collection, options, this);
    };

    /*
    */


    ECTwo.prototype._loadRegions = function(next) {
      var _this = this;
      return this.regions.findAll(this._o.e(next).s(function(regions) {
        return async.forEach(regions, (function(region, next) {
          return region.load(next);
        }), next);
      }));
    };

    return ECTwo;

  })(EventEmitter);

  /*
   returns a controller that handles are EC2 regions
  */


  module.exports = function(options, whitelistRegions) {
    return new ECTwo(options, whitelistRegions);
  };

  /*
  */


  module.exports.utils = {
    objectToTags: require("./utils/objectToTags")
  };

  /*
   Expose all regions within ECTwo
  */


  module.exports.regions = allRegions;

  module.exports.utils = require("./utils");

  /*
   Plugin.js hooks
  */


  module.exports.plugin = function(loader) {
    var awsConfig;
    awsConfig = loader.params("aws");
    return new ECTwo({
      key: awsConfig.key,
      secret: awsConfig.secret
    }, awsConfig.regions);
  };

}).call(this);
