// Generated by CoffeeScript 1.4.0
(function() {
  var async, cstep, flatten, outcome;

  async = require("async");

  cstep = require("cstep");

  outcome = require("outcome");

  flatten = require("flatten");

  module.exports = (function() {
    /*
        Function: 
    
        Parameters:
    */

    function _Class(ectwo, collectionType) {
      this.ectwo = ectwo;
      this.collectionType = collectionType;
    }

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype.load = function() {
      return cstep(this).add(this.ectwo);
    };

    /*
        Function: 
    
        searches through ALL the data centers for servers with the given query
    
        Parameters:
    */


    _Class.prototype.find = cstep(function(query, callback) {
      var _this = this;
      return async.map(this._regions(), (function(region, next) {
        return region[_this.collectionType].find(query).exec(next);
      }), outcome.e(callback).s(function(results) {
        return callback(null, flatten(results));
      }));
    });

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype.findOne = cstep(function(query, callback) {});

    /*
        Function: 
    
        Parameters:
    */


    _Class.prototype._regions = function() {
      return this.ectwo.regions.findAll().sync();
    };

    return _Class;

  })();

}).call(this);
