// Generated by CoffeeScript 1.6.2
(function() {
  var Region, Regions,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Region = require("./region");

  Regions = (function(_super) {
    __extends(Regions, _super);

    /*
    */


    function Regions(ectwoOptions) {
      this.ectwoOptions = ectwoOptions;
      Regions.__super__.constructor.call(this, {
        modelClass: Region
      });
      this._regions = ectwoOptions.regions || require("./utils/allRegions");
    }

    /*
    */


    Regions.prototype._load2 = function(options, next) {
      return next(null, this._regions.map(function(name) {
        return {
          _id: name,
          name: name
        };
      }));
    };

    return Regions;

  })(require("./base/collection"));

  module.exports = Regions;

}).call(this);
