// Generated by CoffeeScript 1.6.2
(function() {
  var childProcess, spawn, sprintf;

  childProcess = require("child_process");

  spawn = childProcess.spawn;

  sprintf = require("sprintf").sprintf;

  exports.require = ["ectwo", "utils"];

  exports.load = function(ectwo, utils) {
    return ectwo.fastener.options().instance.ssh = {
      type: "ssh",
      call: function(options, next) {
        var proc;

        if (arguments.length === 1) {
          next = options;
          options = {};
        }
        if (!options.user) {
          options.user = "root";
        }
        if (!options.key) {
          options.key = utils.defaultKeyPath(this.get("region"), this.get("keyName"));
        }
        next(null, [sprintf("ssh -t -t -i %s %s@%s", options.key, options.user, this.get("dnsName"))]);
        return;
        proc = spawn("ssh", ["-t", "-t", "-i", options.key.replace("~", process.env.HOME), options.user + "@" + this.get("dnsName")]);
        proc.stdout.pipe(process.stdout);
        return proc.stderr.pipe(process.stderr);
      }
    };
  };

}).call(this);
