// Generated by CoffeeScript 1.6.2
(function() {
  var childProcess, spawn;

  childProcess = require("child_process");

  spawn = childProcess.spawn;

  exports.require = ["ectwo", "utils"];

  exports.load = function(ectwo, utils) {
    return ectwo.fastener.options().instance.ssh = {
      type: "ssh",
      onCall: function() {
        return this.root().emit("stopReadLine");
      },
      call: function(options, next) {
        var proc;

        if (arguments.length === 1) {
          next = options;
          options = {};
        }
        if (!options.user) {
          options.user = "root";
        }
        if (!options.key) {
          options.key = utils.defaultKeyPath(this.get("region"), this.get("keyName"));
        }
        next();
        console.log("ssh -t -t -i %s %s@%s", options.key, options.user, this.get("dnsName"));
        proc = spawn("ssh", ["-t", "-t", "-i", options.key.replace("~", process.env.HOME), options.user + "@" + this.get("dnsName")]);
        proc.stdout.pipe(process.stdout);
        proc.stderr.pipe(process.stderr);
        return process.stdin.pipe(proc.stdin);
      }
    };
  };

}).call(this);
