// Generated by CoffeeScript 1.4.0
(function() {
  var Tag, gumbo, toarray, waitForCollectionSync, _;

  gumbo = require("gumbo");

  toarray = require("toarray");

  Tag = require("./tag");

  _ = require("underscore");

  toarray = require("toarray");

  waitForCollectionSync = require("../../utils/waitForCollectionSync");

  /*
  */


  module.exports = (function() {
    /*
    */

    function _Class(item) {
      this.item = item;
      this._ec2 = item._ec2;
      this._collection = new gumbo.Collection([], _.bind(this._createTag, this));
      this._sync = this._collection.synchronizer({
        uniqueKey: "_id",
        load: _.bind(this._loadTags, this),
        timeout: false
      });
      this._sync.load();
    }

    /*
    */


    _Class.prototype.find = function() {
      return this._collection.find.apply(this._collection, arguments);
    };

    /*
    */


    _Class.prototype.findOne = function() {
      return this._collection.findOne.apply(this._collection, arguments);
    };

    /*
    */


    _Class.prototype.create = function(tags, callback, reload) {
      return this._call(tags, "CreateTags", reload !== false, callback);
    };

    /*
    */


    _Class.prototype.remove = function(tags, callback, reload) {
      return this._call(tags, "DeleteTags", reload !== false, callback);
    };

    /*
    */


    _Class.prototype.update = function(tags, callback) {
      var _this = this;
      return this.remove(tags, (function() {
        return _this.create(tags, callback);
      }), false);
    };

    /*
    */


    _Class.prototype._call = function(tags, command, reload, callback) {
      var data, neg, search, self, tagIds;
      self = this;
      tags = toarray(tags);
      data = this._prepareQuery(tags);
      tagIds = tags.map(function(tag) {
        return "" + tag.key + "-" + tag.value;
      });
      search = {};
      search._id = {
        $in: tagIds
      };
      neg = !/DeleteTags/.test(command);
      return this._ec2.call(command, data, outcome.e(callback).s(function(result) {
        console.log(result);
        if (!reload) {
          return callback();
        }
        return waitForCollectionSync(search, self._collection, neg, _.bind(self._reload, self), callback);
      }));
    };

    /*
    */


    _Class.prototype._reload = function(callback) {
      var _this = this;
      return this.item.reload(function() {
        return _this._sync.load(callback);
      });
    };

    /*
    */


    _Class.prototype._prepareQuery = function(tags) {
      var i, tag, toUpdate, _i, _len;
      toUpdate = {
        "ResourceId.1": this.item.get("_id")
      };
      for (i = _i = 0, _len = tags.length; _i < _len; i = ++_i) {
        tag = tags[i];
        toUpdate["Tag." + i + ".Key"] = tag.key;
        toUpdate["Tag." + i + ".Value"] = tag.value;
      }
      return toUpdate;
    };

    /*
    */


    _Class.prototype._createTag = function(collection, item) {
      return new Tag(collection, item, this);
    };

    /*
    */


    _Class.prototype._loadTags = function(options, onLoad) {
      var tags;
      tags = this.item.get("tags");
      return onLoad(null, tags);
    };

    return _Class;

  })();

  /*
  */


  module.exports.transformTags = function(rawData) {
    return toarray(rawData.tagSet).map(function(tagSet) {
      var tag;
      tag = tagSet.item;
      return {
        _id: "" + tag.key + "-" + tag.value,
        key: tag.key,
        value: tag.value
      };
    });
  };

}).call(this);
