// Generated by CoffeeScript 1.4.0
(function() {
  var gumbo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(collection, item, instance) {
      this.instance = instance;
      _Class.__super__.constructor.call(this, collection, item);
    }

    /*
    */


    _Class.prototype.destroy = function(callback) {};

    return _Class;

  })(gumbo.BaseModel);

}).call(this);
