// Generated by CoffeeScript 1.6.2
(function() {
  var BaseModel, gumbo,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  BaseModel = require("../base/model");

  module.exports = (function(_super) {
    __extends(_Class, _super);

    /*
    */


    function _Class(collection, item, tags) {
      this.tags = tags;
      _Class.__super__.constructor.call(this, collection, this.tags.region, item);
    }

    /*
    */


    _Class.prototype.setKey = function(value, callback) {
      return this._resetTags("key", value, callback);
    };

    /*
    */


    _Class.prototype.setValue = function(value, callback) {
      return this._resetTags("value", value, callback);
    };

    /*
    */


    _Class.prototype._destroy = function(callback) {
      return this.tags.remove({
        key: this.get("key"),
        value: this.get("value")
      }, callback);
    };

    /*
     Needed incase these tags are updated - the model doesn't change
    */


    _Class.prototype._resetId = function() {
      return this.update({
        $set: {
          "_id": "" + (this.get('key')) + "-" + (this.get('value'))
        }
      });
    };

    /*
    */


    _Class.prototype._ctags = function() {
      return {
        key: this.get("key"),
        value: this.get("value")
      };
    };

    /*
    */


    _Class.prototype._resetTags = function(property, value, callback) {
      var newTags, oldTags, update;

      oldTags = this._ctags();
      update = {};
      update[property] = value;
      this.update({
        $set: update
      });
      newTags = this._ctags();
      this._resetId();
      return this.tags.update(oldTags, newTags, callback);
    };

    return _Class;

  })(BaseModel);

}).call(this);
