// Generated by CoffeeScript 1.4.0
(function() {
  var BaseCollection, SecurityGroup, outcome,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  BaseCollection = require("../base/collection");

  SecurityGroup = require("./securityGroup");

  outcome = require("outcome");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region) {
      _Class.__super__.constructor.call(this, region, {
        uniqueKey: "groupId",
        modelClass: SecurityGroup
      });
    }

    /*
    */


    _Class.prototype._load = function(onLoad) {
      return this.ec2.call("DescribeSecurityGroups", {}, outcome.e(onLoad).s(function(result) {
        var items;
        if (!result.securityGroupInfo.item) {
          return onLoad(null, []);
        }
        items = result.securityGroupInfo.item instanceof Array ? result.securityGroupInfo.item : [result.securityGroupInfo.item];
        return onLoad(null, items);
      }));
    };

    return _Class;

  })(BaseCollection);

}).call(this);
