// Generated by CoffeeScript 1.6.2
(function() {
  var toarray, type;

  toarray = require("toarray");

  type = require("type-component");

  module.exports = function(data) {
    var tag, tags, tagsAr, _i, _len, _ref;

    tagsAr = toarray((_ref = data.tagSet) != null ? _ref.item : void 0);
    tags = {};
    for (_i = 0, _len = tagsAr.length; _i < _len; _i++) {
      tag = tagsAr[_i];
      if (type(tag.value) === "object") {
        continue;
      }
      tags[tag.key] = tag.value;
    }
    return tags;
  };

}).call(this);
