// Generated by CoffeeScript 1.4.0
(function() {
  var objectToTags, tagsToObject, _;

  _ = require("underscore");

  objectToTags = require("./objectToTags");

  tagsToObject = require("./tagsToObject");

  /*
  */


  module.exports = function(from, to, additionalTags, next) {
    var tags;
    if (arguments.length === 3) {
      next = additionalTags;
      additionalTags = {};
    }
    tags = tagsToObject(from.get("tags") || []);
    _.extend(tags, additionalTags);
    return to.tags.create(objectToTags(tags), next);
  };

}).call(this);
