// Generated by CoffeeScript 1.4.0
(function() {
  var outcome, stepc;

  stepc = require("stepc");

  outcome = require("outcome");

  module.exports = function(region, options, callback) {
    var newInstanceId, o;
    ectwo_log.log("%s: create server", region.name);
    o = outcome.e(callback);
    newInstanceId = null;
    return stepc.async(function() {
      return region.ec2.call("RunInstances", {
        "ImageId": options.imageId,
        "MinCount": options.count || 1,
        "MaxCount": options.count || 1,
        "InstanceType": options.flavor || "m1.small"
      }, this);
    }, o.s(function(result) {
      newInstanceId = result.instancesSet.item.instanceId;
      return region.instances.syncAndFindOne({
        _id: newInstanceId
      }, this);
    }), callback);
  };

}).call(this);
