// Generated by CoffeeScript 1.6.2
(function() {
  var objectToTags, outcome, stepc;

  stepc = require("stepc");

  outcome = require("outcome");

  objectToTags = require("./objectToTags");

  /*
  */


  module.exports = function(region, options, callback) {
    var newInstanceId, o;

    region.logger.info("create server image=" + options.imageId + ", flavor=" + options.flavor);
    o = outcome.e(callback);
    newInstanceId = null;
    return stepc.async(function() {
      return region.ec2.call("RunInstances", {
        "ImageId": options.imageId,
        "MinCount": options.count || 1,
        "MaxCount": options.count || 1,
        "InstanceType": options.flavor || options.type || "m1.small"
      }, this);
    }, o.s(function(result) {
      newInstanceId = result.instancesSet.item.instanceId;
      region.logger.info("created server instance=" + newInstanceId);
      return region.instances.syncAndFindOne({
        _id: newInstanceId
      }, this);
    }), o.s(function(instance) {
      var tags,
        _this = this;

      tags = options.tags || {};
      tags.createdAt = Date.now();
      return instance.tags.create(objectToTags(tags), o.s(function() {
        return _this(null, instance);
      }));
    }), callback);
  };

}).call(this);
