// Generated by CoffeeScript 1.6.2
(function() {
  var outcome;

  outcome = require("outcome");

  /*
  */


  module.exports = function(collection, search, callback) {
    return collection.findOne(search, outcome.e(callback).s(function(result) {
      if (!result) {
        return new Error("Unable to find one with query=" + (JSON.stringify(search)));
      }
      return callback(null, result);
    }));
  };

}).call(this);
