// Generated by CoffeeScript 1.6.2
(function() {
  module.exports = {
    cleanObj: function(obj) {
      var key;

      for (key in obj) {
        if (!obj[key]) {
          delete obj[key];
        }
      }
      return obj;
    }
  };

}).call(this);
