// Generated by CoffeeScript 1.6.2
(function() {
  var fs, path;

  fs = require("fs");

  path = require("path");

  /*
  */


  fs.readdirSync(__dirname).forEach(function(file) {
    var basename;

    basename = path.basename(file);
    if (basename === "index" || !/(js|coffee)$/.test(file)) {
      return;
    }
    return exports[basename] = require("" + __dirname + "/" + basename);
  });

}).call(this);
