// Generated by CoffeeScript 1.6.2
(function() {
  var winston;

  winston = require("winston");

  /*
  */


  exports.child = function(message, parent) {
    var logger,
      _this = this;

    logger = {
      child: function(message) {
        return exports.child(message, logger);
      },
      prefix: function() {
        return (parent ? parent.prefix() + " " : "") + message;
      }
    };
    ["info", "warn", "error"].forEach(function(level) {
      return logger[level] = function() {
        arguments[0] = logger.prefix() + " " + arguments[0];
        return winston[level].apply(winston, arguments);
      };
    });
    return logger;
  };

}).call(this);
