// Generated by CoffeeScript 1.4.0
(function() {

  module.exports = function(obj) {
    var key, tags;
    tags = [];
    for (key in obj) {
      tags.push({
        key: key,
        value: obj[key]
      });
    }
    return tags;
  };

}).call(this);
