// Generated by CoffeeScript 1.4.0

/*
*/


(function() {

  module.exports = function(tags) {
    var obj, tag, _i, _len;
    obj = {};
    for (_i = 0, _len = tags.length; _i < _len; _i++) {
      tag = tags[_i];
      obj[tag.key] = tag.value;
    }
    return obj;
  };

}).call(this);
