// Generated by CoffeeScript 1.4.0
(function() {
  var outcome, _;

  _ = require("underscore");

  outcome = require("outcome");

  /*
    EC2 is rather unreliable - changes are made asynchronously
  */


  module.exports = function(search, collection, find, reload, callback, tries) {
    if (tries == null) {
      tries = 20;
    }
    return reload(function() {
      return collection.findOne(search, outcome.e(callback).s(function(item) {
        var retry;
        retry = !!find !== !!item;
        if (retry) {
          if (!tries) {
            return callback(new Error("unable to meet condition \"" + (JSON.stringify(search)) + "\" for waitForCollectionSync"));
          }
          return setTimeout(_.bind(module.exports, module, search, collection, find, reload, callback, tries - 1), 1000);
        }
        return callback(null, item);
      }));
    });
  };

}).call(this);
