// Generated by CoffeeScript 1.6.2
(function() {
  var hurryUp, outcome, _;

  _ = require("underscore");

  outcome = require("outcome");

  hurryUp = require("hurryUp");

  /*
    EC2 is rather unreliable - changes are made asynchronously
  */


  module.exports = function(search, collection, find, reload, callback) {
    var load;

    load = function(callback) {
      collection.logger.info("wait for sync time left=" + this._timeLeft + ",", search);
      return reload(function() {
        return collection.findOne(search, outcome.e(callback).s(function(item) {
          var retry;

          retry = !!find !== !!item;
          if (retry) {
            return callback(new Error("unable to meet condition \"" + (JSON.stringify(search)) + "\" for waitForCollectionSync"));
          }
          collection.logger.info("synchronized", search);
          return callback(null, item);
        }));
      });
    };
    return hurryUp(load, {
      retry: true,
      retryTimeout: 1000 * 3,
      timeout: 1000 * 60 * 20
    })(callback);
  };

}).call(this);
