// Generated by CoffeeScript 1.4.0
(function() {
  var outcome, sift, skipIfSynced;

  sift = require("sift");

  outcome = require("outcome");

  module.exports = function(item, search, callback) {
    var checkState,
      _this = this;
    checkState = function() {
      return skipIfSynced(item, search, callback, function() {
        return setTimeout(checkState, 1000 * 3);
      });
    };
    return checkState();
  };

  module.exports.skipIfSynced = skipIfSynced = function(item, search, end, next) {
    var self, stateTest,
      _this = this;
    stateTest = sift(search);
    self = this;
    return item.reload(outcome.e(end).s(function(result) {
      if (stateTest.test(item.get())) {
        return end();
      } else {
        return next();
      }
    }));
  };

}).call(this);
