// Generated by CoffeeScript 1.4.0
(function() {
  var hurryUp, outcome, sift, skipIfSynced;

  sift = require("sift");

  outcome = require("outcome");

  hurryUp = require("hurryup");

  /*
  */


  module.exports = function(item, search, callback) {
    var load;
    load = function(callback) {
      item.logger.info("wait until sync time left=" + this._timeLeft + ",", search);
      return skipIfSynced(item, search, callback, outcome.e(callback).s(function() {
        return callback(new Error("unable to meet condition " + (JSON.stringify(search)) + " with item"));
      }));
    };
    return hurryUp(load, {
      retry: true,
      timeout: 1000 * 60 * 20,
      retryTimeout: 1000 * 3
    })(callback);
  };

  /*
  */


  module.exports.skipIfSynced = skipIfSynced = function(item, search, end, next) {
    var stateTest,
      _this = this;
    stateTest = sift(search);
    return item.reload(outcome.e(function(err) {
      console.error(err);
      return end();
    }).s(function(result) {
      console.log(item.get());
      if (stateTest.test(item.get())) {
        return end();
      } else {
        return next();
      }
    }));
  };

}).call(this);
