// Generated by CoffeeScript 1.4.0
(function() {
  var outcome, sift, skipIfSynced;

  sift = require("sift");

  outcome = require("outcome");

  module.exports = function(item, search, callback) {
    var checkState, tries,
      _this = this;
    tries = 100;
    checkState = function() {
      tries--;
      return skipIfSynced(item, search, callback, outcome.e(callback).s(function() {
        if (!tries) {
          callback(new Error("unable to meet condition " + (JSON.stringify(search)) + " with item"));
        }
        return setTimeout(checkState, 1000 * 3);
      }));
    };
    return checkState();
  };

  module.exports.skipIfSynced = skipIfSynced = function(item, search, end, next) {
    var stateTest,
      _this = this;
    stateTest = sift(search);
    return item.reload(outcome.e(end).s(function(result) {
      if (stateTest.test(item.get())) {
        return end();
      } else {
        return next();
      }
    }));
  };

}).call(this);
