// Generated by CoffeeScript 1.4.0
(function() {
  var gumbo, waitForCollectionSync, _,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gumbo = require("gumbo");

  _ = require("underscore");

  waitForCollectionSync = require("../../utils/waitForCollectionSync");

  module.exports = (function(_super) {

    __extends(_Class, _super);

    /*
    */


    function _Class(region, options) {
      this.region = region;
      this.options = options;
      this.ec2 = region.ec2;
      if (!options.modelClass) {
        throw new Error("modelClass must be present");
      }
      _Class.__super__.constructor.call(this, [], _.bind(this._createModel, this));
      this.sync = this.synchronizer({
        uniqueKey: "_id",
        load: _.bind(this._load, this),
        timeout: options.timeout || 1000 * 60
      });
    }

    /*
    */


    _Class.prototype.load = function(callback) {
      if (!this._initialLoad) {
        this._initialLoad = true;
        return this.sync.start(callback);
      }
      return this.sync.load(callback);
    };

    /*
    */


    _Class.prototype.syncAndFindOne = function(options, callback) {
      return waitForCollectionSync(options, this, true, _.bind(this.sync.load, this.sync), callback);
    };

    /*
    */


    _Class.prototype._createModel = function(collection, item) {
      var m;
      m = new this.options.modelClass(collection, this.region, this._transformItem(item));
      return m;
    };

    /*
    */


    _Class.prototype._load = function(onLoad) {
      throw new Error("must be overridden");
    };

    /*
    */


    _Class.prototype._transformItem = function(item) {
      item.region = this.region.get("name");
      return item;
    };

    /*
    */


    _Class.prototype._load = function() {};

    return _Class;

  })(gumbo.Collection);

}).call(this);
