// Generated by CoffeeScript 1.6.2
(function() {
  var Volume, Volumes, bindable, outcome, toarray, utils,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  Volume = require("./volume");

  outcome = require("outcome");

  toarray = require("toarray");

  utils = require("../../utils");

  bindable = require("bindable");

  Volumes = (function(_super) {
    __extends(Volumes, _super);

    /*
    */


    function Volumes(region) {
      Volumes.__super__.constructor.call(this, {
        modelClass: bindable.Object,
        region: region
      });
    }

    /*
    */


    Volumes.prototype._load2 = function(options, next) {
      return this.api.call("DescribeAvailabilityZones", search, next);
    };

    return Volumes;

  })(require("../../base/collection"));

  module.exports = Volumes;

}).call(this);
