// Generated by CoffeeScript 1.4.0
(function() {
  var Region, async, aws;

  aws = require("aws-lib");

  async = require("async");

  Region = require("./region");

  module.exports = (function() {

    function _Class(options, whitelist) {
      this.options = options;
      this.whitelist = whitelist != null ? whitelist : ["us-west-1", "us-west-2", "us-east-1", "eu-west-1", "sa-east-1", "ap-southeast-1", "ap-southeast-2", "ap-northeast-1"];
      this.load();
    }

    _Class.prototype.load = function(callback) {
      var _this = this;
      if (callback == null) {
        callback = (function() {});
      }
      this.regions = [];
      return async.forEach(this.whitelist, (function(regStr, next) {
        var ec2, host;
        host = "ec2." + regStr + ".amazonaws.com";
        ec2 = aws.createEC2Client(_this.options.key, _this.options.secret, {
          host: host
        });
        return _this.regions.push(new Region(regStr, ec2).load(next));
      }), callback);
    };

    return _Class;

  })();

}).call(this);
