// Generated by CoffeeScript 1.6.2
(function() {
  exports.load = function() {
    return {
      defaultKeyPath: function(region, name) {
        return "~/keys/" + region + "/" + name + ".pem";
      }
    };
  };

}).call(this);
